umccr/htsget-rs

htsget-search/src/htsget/bam.rs
htsget-search/src/htsget/from_storage.rs
htsget-search/src/storage/mod.rs

Merge byte ranges

---

htsget-search/src/storage/mod.rs

Add tests for BytesRange

---

htsget-search/src/htsget/bam_search.rs
htsget-search/src/htsget/mod.rs
htsget-search/src/storage/local.rs

Fixes #8 
I've attempted to implement the class attribute for reads, according to the spec.
Let me know if I'm on the right track, because I'm not certain that this is correct.

Implement class attribute for reads

---

htsget-search/src/htsget/mod.rs

Just a small PR to fix [this TODO](https://github.com/chris-zen/htsget-mvp/blob/3c172638ac58ff31dd730e73de2f52aa0b0febdd/htsget-search/src/htsget/mod.rs#L131).

Add the rest of the builder methods to Query

---

htsget-search/src/storage/local.rs

I added some tests for `LocalStorage::url`. 
Some of them, especially `url_of_non_existing_key`, `url_of_folder` and `url_with_forbidden_path`, might be considered redundant because they test something that is more or less tested by its `LocalStorage::get` counterparts. So if needed I can get rid of them. 
If more tests are needed just tell me. I'm waiting to read your feeback!

Add some tests for `LocalStorage::url`

---

htsget-search/src/htsget/bam_search.rs
htsget-search/src/storage/mod.rs

Add storage model tests, closes #24.

Storage model tests

---

htsget-search/src/storage/local.rs

Closes #26 
Now the Range header only gets added if either range_start or
range_end isn't empty

Fix Local Storage always adding the Range header

---

htsget-search/src/htsget/bam_search.rs

Closes #17
Starting from what was already accomplished in #20, with some minor changes. 
I have been debugging to understand why the three ranges in the `search_reference_name_with_seq_range` get merged. It seems to me that something is wrong in the current implementation. 
In the test the content of block_ranges (which should contain where the blocks start and end) is the following:
```
[htsget-search/src/htsget/bam_search.rs:44] block_ranges = {
1590681: 1912645,
555224: 627987,
1065952: 1350270,
977196: 1065952,
499249: 555224,
1350270: 1454565,
1912645: 2060795,
256721: 499249,
4668: 256721,
627987: 824361,
2060795: 2112141,
824361: 977196,
1454565: 1590681,
}
```
We can see  824361 is linked to 977196. If I understand correctly, that means what is between those numbers is a block. …

Calculate BAM byte ranges more accurately

---

htsget-search/src/htsget/bam_search.rs

This PR improves the ranges (makes them smaller and more accurate) htsget gives when asked for the header of a BAM file. It works just like the VCF support works now, it reads the header, so it knows where it ends.
The only thing I'm not sure about is deleting `DEFAULT_BAM_HEADER_LENGTH`. I thought it wasn't needed any more, because now we can get the exact size of the header, but it is also used in the `GetOptions` for getting the path. [Example](https://github.com/umccr/htsget-rs/blob/b3cb114c11968e93aee3fca4412bc561a41b3373/htsget-search/src/htsget/bam_search.rs#L134). The point is I don't know why you need that length to get the path of the file. In the local implementation it is [completely ignored](https://github.com/umccr/htsget-rs/blob/b3cb114c11968e93aee3fca4412bc561a41b3373/htsge …

Improve the bytes ranges for the BAM header

---

htsget-devtools/Cargo.toml
htsget-devtools/src/bam.rs
htsget-devtools/src/bcf.rs
htsget-devtools/src/vcf.rs
htsget-search/Cargo.toml
htsget-search/src/htsget/bam_search.rs
htsget-search/src/htsget/bcf_search.rs
htsget-search/src/htsget/cram_search.rs
htsget-search/src/htsget/mod.rs
htsget-search/src/htsget/search.rs
htsget-search/src/htsget/vcf_search.rs
htsget-search/src/storage/local.rs

As @CastilloDel and I spoke about, we should have a more stable version of noodles than the master branch, so that our code doesn't break as often.

Track crates.io version of noodles

---

htsget-http-core/src/error.rs

Fixes issue https://github.com/umccr/htsget-rs/issues/91
Note: A local `cargo test` does not seem to make any of the tests fail... this should be a red flag since it changes the shape of the (error) responses? :-S

Wrapping up htsget around the error and message responses

---

htsget-http-actix/Cargo.toml
htsget-http-core/Cargo.toml
htsget-http-lambda/Cargo.toml
htsget-search/Cargo.toml

(except querymap) and avoid pulling full tokio in, we just need macros and rt-multi-thread.

Bump many deps

---

deploy/README.md
deploy/lib/htsget-http-lambda-stack.ts
deploy/package.json
htsget-http-actix/Cargo.toml
htsget-search/Cargo.toml
htsget-search/src/storage/aws.rs
htsget-search/src/storage/local.rs
htsget-search/src/storage/mod.rs
htsget-search/src/storage/ticket_server.rs
htsget-test-utils/Cargo.toml

Changes:
* Update deploy README.md.
* Add trace calls deployed server.
* Remove openssl development library dependencies from non-test targets.
* Simplify some tests by using reqwest.

Changes to deployment

---

htsget-actix/Cargo.toml
htsget-config/Cargo.toml
htsget-http/Cargo.toml
htsget-lambda/Cargo.toml
htsget-search/Cargo.toml
htsget-test/Cargo.toml

Thanks @victorskl for rising this.

Set MSRV on all workspace crates

---

Cargo.lock
htsget-actix/Cargo.toml
htsget-config/Cargo.toml
htsget-http/Cargo.toml
htsget-lambda/Cargo.toml
htsget-search/Cargo.toml
htsget-search/src/htsget/search.rs
htsget-search/src/storage/mod.rs
htsget-test/Cargo.toml
htsget-test/src/server_tests.rs

For some reason the changes to `Cargo.lock` weren't picked up in the [previous PR](https://github.com/umccr/htsget-rs/pull/150). I've added those changes here, and updated some dependencies.

Update cargo files

---

Cargo.lock
htsget-actix/Cargo.toml
htsget-config/Cargo.toml
htsget-http/Cargo.toml
htsget-lambda/Cargo.toml
htsget-search/Cargo.toml
htsget-test/Cargo.toml

See https://github.com/MarcoIeni/release-plz/issues/507#issuecomment-1420254400

Downgrade release after fixing cargo publish circular dep issues

---

deploy/cdk.json
deploy/config/config_prod_umccr.toml
deploy/lib/htsget-lambda-stack.ts

* Bumped Lambda timeout to 28s
* Fixed typo storage_type in config

Adjusted UMCCR PROD config

---

htsget-config/README.md
htsget-config/src/resolver.rs
htsget-config/src/storage/s3.rs
htsget-search/src/htsget/from_storage.rs
htsget-search/src/storage/aws.rs

Adds a config option for setting path style for S3 storage backends.

Add path_style config option for S3 storage

---

Cargo.lock
htsget-actix/Cargo.toml
htsget-config/Cargo.toml
htsget-lambda/Cargo.toml
htsget-search/Cargo.toml
htsget-test/Cargo.toml

* Bumps a few dependencies.
* Removes some unused dependencies.

build: bump deps

---

.github/workflows/release.yml

Sorry, still not fixed!
* Fix toolchain on release workflow.

ci: fix release workflow toolchain

---

Cargo.lock
deploy/package-lock.json
deploy/package.json
htsget-actix/Cargo.toml
htsget-actix/src/handlers/mod.rs
htsget-test/Cargo.toml
htsget-test/src/server_tests.rs

Bump up deploy deps, getting this ready to be deployed on the UoM demo account alongside Elsa.
/cc @andrewpatto

Bump up deploy packages, also solves CVE-2023-35165 and CVE-2022-25883

---

.github/workflows/benchmarking.yml
.github/workflows/build.yml
.github/workflows/release.yml
.github/workflows/tests.yml
deploy/Dockerfile
deploy/README.md
htsget-search/src/storage/mod.rs

@mmalenic Feel free to squash/refactor this while we are timezone unsync'd (i.e I'm sleeping) ;)
Most probably folks at GDI/NBIS will need this to develop on their SDA support et al?

Docker release support

---

htsget-search/src/storage/s3.rs

* Add more detailed s3 error message.

refactor(s3): add more detailed error message

---

.github/workflows/build.yml

Fixes failing GHA builds going ENOSPC introduced by PR #209.

Docker CI fix

---

deploy/Dockerfile

See https://nickjanetakis.com/blog/docker-tip-54-fixing-connection-reset-by-peer-or-similar-errors.

Docker BIND convenience environment variables

---

htsget-axum/README.md

* Add example for running htsget-rs with Crypt4GH.

docs: add example on how to use Crypt4GH with the htsget-rs server

---

htsget-actix/src/handlers/mod.rs
htsget-actix/src/lib.rs
htsget-actix/src/middleware/auth.rs
htsget-axum/src/middleware/auth.rs
htsget-axum/src/server/data.rs
htsget-axum/src/server/mod.rs
htsget-axum/src/server/ticket.rs
htsget-config/docs/examples/auth.toml
htsget-config/docs/examples/basic.toml
htsget-config/docs/examples/c4gh.toml
htsget-config/docs/examples/s3_storage.toml
htsget-config/docs/examples/tls_data_server.toml
htsget-config/docs/examples/tls_ticket_server.toml
htsget-config/docs/examples/url_storage.toml
htsget-http/src/middleware/auth.rs
htsget-test/src/http/cors.rs

* Fixes bugs with new authorization logic from https://github.com/umccr/htsget-rs/pull/312.
* Correctly use mirror and any options for CORS.
* Adds fallback service to actix routes.

fix: authorization flow bugs and CORS changes

---

.github/workflows/build.yml
.github/workflows/release.yml
.github/workflows/tests.yml

Fixes https://github.com/umccr/htsget-rs/security/code-scanning warnings...

build(ci): Fix CodeQL warnings about workflow permissions
