umccr/htsget-rs

.gitignore
If we aren't going to upload the Cargo.lock to the repository, I think we are better off adding it to the .gitignore, so it doesn't get added by accident
=> Add Cargo.lock to the .gitignore

htsget-search/src/htsget/bam_search.rs, htsget-search/src/htsget/mod.rs, htsget-search/src/storage/local.rs, htsget-search/src/storage/mod.rs
Closes #27 
With this change there is only one way to represent a Query or a Url that
doesn't specify a class.
=> Remove duplicity in Query, UrlOptions and Url

htsget-search/src/htsget/bam_search.rs
Closes #38 
I reviewed the new values and they seem to be correct, so I updated the tests. Probably the previous values were wrong, because I got them with Noodles before https://github.com/zaeleus/noodles/issues/23 and https://github.com/zaeleus/noodles/issues/21 
This PR will make the tests pass in main
=> Adapt tests to noodles changes

htsget-search/src/storage/local.rs, htsget-search/src/storage/mod.rs
Provides the file size through the storage trait, which is useful for BAM search, and potentially CRAM, closes #15.
=> Providing the file size through the Storage abstraction.

htsget-devtools/src/bam.rs, htsget-devtools/src/bcf.rs, htsget-devtools/src/vcf.rs, htsget-search/src/htsget/bam_search.rs, htsget-search/src/htsget/bcf_search.rs, htsget-search/src/htsget/cram_search.rs, htsget-search/src/htsget/from_storage.rs, htsget-search/src/htsget/mod.rs, htsget-search/src/htsget/search.rs, htsget-search/src/htsget/vcf_search.rs
This refactors some commonalities across the formats, by creating a trait. Currently there is further duplicate code, however this will be removed upon completing this pull request.
Closes #48.
=> Refactor commonalities across all formats.

htsget-http-core/src/service_info.rs
This is how it works in the reference implementation and it also seems clearer. Reporting in both endpoints (reads and variants) the formats supported in the whole server can cause confusions. For example, if I got from 'reads/service-info' a response saying 'VCF' is a supported format, I could be really surprised when requesting a 'VCF' format to the reads endpoint ended in an unsupported format error.
Didn't notice this when I implemented it, but it seems better now.
=> Make service-info only show the formats available in that endpoint

htsget-http-core/src/json_response.rs
Another little fix to something I noticed comparing with the reference implementation. 
The JSON response is supposed to be wrapped in a htsget object.
=> Add hstget container to response

.github/workflows/action.yml, htsget-http-actix/Cargo.toml, htsget-http-actix/src/handlers/blocking/get.rs, htsget-http-actix/src/handlers/blocking/mod.rs, htsget-http-actix/src/handlers/blocking/post.rs, htsget-http-actix/src/handlers/get.rs, htsget-http-actix/src/handlers/mod.rs, htsget-http-actix/src/handlers/post.rs, htsget-http-actix/src/handlers/pretty_json.rs, htsget-http-actix/src/lib.rs, htsget-http-actix/src/main.rs, htsget-http-core/Cargo.toml, htsget-http-core/src/json_response.rs, htsget-http-core/src/lib.rs, htsget-http-core/src/service_info.rs, htsget-search/Cargo.toml, htsget-search/src/htsget/mod.rs, htsget-search/src/storage/mod.rs
Closes #67 
This was an issue with multiple conflicting versions of tokio. Actix-web v3 only supports tokio 0.2, however our project uses tokio 1.x. This PR updates to Actix-web v4, which is still in beta. This fixes the issues relating to the server not returning proper responses with curl examples. All the curl examples should now work, for both blocking and async code.
=> Fix runtime panics from curl

.github/workflows/action.yml, htsget-search/src/storage/aws.rs
This PR changes the s3-server tests for `AwsS3Storage`, so that a test server is only initialized once. This allows tests to be run in parallel.
=> Allow AwsS3Storage tests to be run in parallel

htsget-config/Cargo.toml, htsget-config/src/config.rs, htsget-config/src/regex_resolver.rs, htsget-http-actix/Cargo.toml, htsget-http-actix/src/handlers/service_info.rs, htsget-http-actix/src/lib.rs, htsget-http-actix/src/main.rs, htsget-http-core/src/lib.rs, htsget-http-core/src/service_info.rs, htsget-http-lambda/Cargo.toml, htsget-http-lambda/src/handlers/service_info.rs, htsget-http-lambda/src/lib.rs, htsget-http-lambda/src/main.rs, htsget-search/Cargo.toml, htsget-search/src/htsget/bam_search.rs, htsget-search/src/htsget/cram_search.rs, htsget-search/src/htsget/from_storage.rs, htsget-search/src/htsget/mod.rs, htsget-search/src/htsget/vcf_search.rs, htsget-search/src/storage/aws.rs, htsget-search/src/storage/axum_server.rs, htsget-search/src/storage/local.rs, htsget-search/src/storage/mod.rs, htsget-test-utils/src/server_tests.rs
This PR enables choosing between using `LocalStorage` and `AwsS3Storage`. It also refactors a bit of code in the some of the crates.
Changes:
* Add `StorageType` config option which allows choosing between `LocalStorage` and `AwsS3Storage`.
* Refactor some config options.
* Update usage text.
* Add a few tests for the config options.
Further improvements may involve adding the ability to setup multiple resolvers, that map to arbitrary storage types. For example, an id starting with "aws-{id}" could map to an `AwsS3Storage`, whereas an id starting with "local-{id}" could map to `LocalStorage`.
=> Enable choosing between storage types.

data/events/event_get.json, data/events/event_parameterized_get.json, data/events/event_parameterized_post.json, data/events/event_parameterized_post_class_header.json, data/events/event_post.json, htsget-config/src/config.rs, htsget-http-actix/README.md, htsget-http-actix/src/handlers/get.rs, htsget-http-actix/src/handlers/post.rs, htsget-http-actix/src/handlers/service_info.rs, htsget-http-actix/src/lib.rs, htsget-http-actix/src/main.rs, htsget-http-core/src/lib.rs, htsget-http-lambda/src/lib.rs, htsget-http-lambda/src/main.rs, htsget-search/src/htsget/bam_search.rs, htsget-search/src/htsget/bcf_search.rs, htsget-search/src/htsget/cram_search.rs, htsget-search/src/htsget/from_storage.rs, htsget-search/src/htsget/mod.rs, htsget-search/src/htsget/vcf_search.rs, htsget-search/src/storage/axum_server.rs, htsget-search/src/storage/local.rs, htsget-search/src/storage/mod.rs, htsget-test-utils/src/server_tests.rs
Fixes #84 
Changes:
* `LocalStorage` now returns the correct url paths which correspond to the ticket server.
* Fix numerous tests which were broken.
* Update README.md in htsget-http-lambda.
=> Fix localstorage path

htsget-http-actix/benches/request_benchmarks.rs, htsget-http-core/src/error.rs, htsget-http-core/src/http_core.rs, htsget-search/Cargo.toml, htsget-search/src/htsget/bam_search.rs, htsget-search/src/htsget/bcf_search.rs, htsget-search/src/htsget/cram_search.rs, htsget-search/src/htsget/search.rs, htsget-search/src/htsget/vcf_search.rs
Fixes #85
The following PR fixes out of order urls in response tickets, which were caused by using `FuturesUnordered`, instead of `FuturesOrdered`.
Changes:
* Change `FuturesUnordered` to `FuturesOrdered`.
* Bump noodles to version 0.24.
=> Out of order urls

htsget-config/src/config.rs, htsget-config/src/regex_resolver.rs, htsget-http-actix/Cargo.toml, htsget-http-actix/benches/request_benchmarks.rs, htsget-http-actix/src/lib.rs, htsget-http-actix/src/main.rs, htsget-http-core/Cargo.toml, htsget-http-core/src/error.rs, htsget-http-core/src/http_core.rs, htsget-http-core/src/lib.rs, htsget-http-core/src/query_builder.rs, htsget-http-core/src/service_info.rs, htsget-http-lambda/Cargo.toml, htsget-http-lambda/src/handlers/mod.rs, htsget-http-lambda/src/lib.rs, htsget-http-lambda/src/main.rs, htsget-search/Cargo.toml, htsget-search/benches/search_benchmarks.rs, htsget-search/src/htsget/bam_search.rs, htsget-search/src/htsget/bcf_search.rs, htsget-search/src/htsget/cram_search.rs, htsget-search/src/htsget/mod.rs, htsget-search/src/htsget/search.rs, htsget-search/src/htsget/vcf_search.rs, htsget-search/src/storage/aws.rs, htsget-search/src/storage/local.rs, htsget-search/src/storage/mod.rs, htsget-search/src/storage/ticket_server.rs, htsget-test-utils/Cargo.toml, htsget-test-utils/src/server_tests.rs
Closes #112 
Changes:
* Improve errors so that they are more informative, propagating information from their cause to the http responses.
* Avoid reading indices unless it is necessary.
=> Improve descriptiveness of errors

htsget-search/src/htsget/cram_search.rs, htsget-search/src/htsget/search.rs
Changes:
* Return an error when no chunks are found in BGZF indices.
* Return an error if no entries are found in CRAI.
* Sort BGZF indices, and search through GZI only once.
=> Small changes related to indices

htsget-config/Cargo.toml, htsget-config/src/config.rs, htsget-config/src/regex_resolver.rs, htsget-http-actix/Cargo.toml, htsget-http-actix/src/handlers/get.rs, htsget-http-actix/src/handlers/post.rs, htsget-http-actix/src/handlers/service_info.rs, htsget-http-actix/src/lib.rs, htsget-http-actix/src/main.rs, htsget-http-core/src/http_core.rs, htsget-http-core/src/post_request.rs, htsget-http-core/src/query_builder.rs, htsget-http-core/src/service_info.rs, htsget-http-lambda/src/handlers/get.rs, htsget-http-lambda/src/handlers/post.rs, htsget-http-lambda/src/handlers/service_info.rs, htsget-http-lambda/src/lib.rs, htsget-http-lambda/src/main.rs, htsget-search/src/htsget/bam_search.rs, htsget-search/src/htsget/bcf_search.rs, htsget-search/src/htsget/cram_search.rs, htsget-search/src/htsget/from_storage.rs, htsget-search/src/htsget/mod.rs, htsget-search/src/htsget/search.rs, htsget-search/src/htsget/vcf_search.rs, htsget-search/src/storage/aws.rs, htsget-search/src/storage/local.rs, htsget-search/src/storage/mod.rs, htsget-search/src/storage/ticket_server.rs
The following PR introduces changes related to logging and tracing.
Changes:
* Add various tracing logs and tracing instrument calls to help with debugging.
* Fixes issue with reading files, where an un-buffered reader was resulting in inefficiency due to many sys-calls. All read calls now use buffered reads.
=> Tracing and buffered reads

deploy/bin/htsget-http-lambda.ts, deploy/lib/htsget-http-lambda-stack.ts, doc/img/ga4gh-logo.svg, htsget-http-actix/src/lib.rs, htsget-http-actix/src/main.rs, htsget-http-core/src/lib.rs, htsget-http-core/src/service_info.rs, htsget-http-lambda/src/handlers/service_info.rs, htsget-http-lambda/src/lib.rs, htsget-http-lambda/src/main.rs, htsget-search/benches/search_benchmarks.rs, htsget-search/src/htsget/cram_search.rs, htsget-search/src/htsget/from_storage.rs, htsget-search/src/htsget/mod.rs, htsget-search/src/htsget/search.rs, htsget-search/src/lib.rs, htsget-search/src/storage/aws.rs, htsget-search/src/storage/data_server.rs, htsget-search/src/storage/local.rs, htsget-search/src/storage/mod.rs, htsget-test-utils/src/http_tests.rs, htsget-test-utils/src/lib.rs, htsget-test-utils/src/server_tests.rs
Re-exports htsget-config for the other crates, and makes some htsget-search functions public for use as a dependency.
=> Re-export htsget-config and add more pub functions

htsget-search/src/htsget/bam_search.rs, htsget-search/src/htsget/bcf_search.rs, htsget-search/src/htsget/cram_search.rs, htsget-search/src/htsget/mod.rs, htsget-search/src/htsget/search.rs, htsget-search/src/htsget/vcf_search.rs
Refactors htsget-search to better use the noodles [`Interval`](https://docs.rs/noodles/latest/noodles/core/region/struct.Interval.html). Removes `ReferenceSequenceInfo`, and simplifies some logic when converting the start and end positions to noodles [`Position`](https://docs.rs/noodles/latest/noodles/core/struct.Position.html).
=> Refactor htsget-search to make better use of noodles

htsget-search/src/htsget/bam_search.rs, htsget-search/src/htsget/bcf_search.rs, htsget-search/src/htsget/cram_search.rs, htsget-search/src/htsget/vcf_search.rs
Makes the search structs public for use as a dependency. This was meant to be included in #121.
=> Make search structs public

deploy/lib/htsget-http-lambda-stack.ts
Uses the new HTSGET_RESOLVERS environment variable in the deploy example
=> build(deploy): add resolvers environment variable to deploy example

Cargo.lock, htsget-lambda/Cargo.toml, htsget-search/Cargo.toml, htsget-search/src/htsget/bam_search.rs, htsget-search/src/htsget/bcf_search.rs, htsget-search/src/htsget/cram_search.rs, htsget-search/src/htsget/from_storage.rs, htsget-search/src/htsget/mod.rs, htsget-search/src/htsget/search.rs, htsget-search/src/htsget/vcf_search.rs, htsget-search/src/storage/aws.rs, htsget-search/src/storage/data_server.rs, htsget-search/src/storage/local.rs, htsget-search/src/storage/mod.rs
=> Remove s3-server and dependencies

deploy/lib/htsget-lambda-stack.ts
* The $default route protect/auth OPTIONS request that is made during browser CORS preflight request purpose. OPTIONS request should be reachable without auth. See https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-cors.html
=> Use explicit routes GET, POST with {proxy+} path

Cargo.lock, htsget-actix/Cargo.toml, htsget-actix/src/lib.rs, htsget-actix/src/main.rs, htsget-config/Cargo.toml, htsget-config/src/config/mod.rs, htsget-http/Cargo.toml, htsget-http/src/service_info.rs, htsget-lambda/Cargo.toml, htsget-lambda/src/lib.rs, htsget-lambda/src/main.rs, htsget-search/Cargo.toml, htsget-search/src/storage/data_server.rs, htsget-test/Cargo.toml, htsget-test/src/http_tests.rs, htsget-test/src/server_tests.rs
Closes #158 
This PR refactors `htsget-tests` to avoid a circular dependency with `htsget-search` and `htsget-http`.
* Use generic types in `http-tests` to avoid using the structs in `htsget-search` and `htsget-http`.
* Specify expected responses using `serde_json` [`Value`](https://docs.rs/serde_json/latest/serde_json/value/enum.Value.html). This also probably makes the tests more robust as they no longer dependent on the implementation of the `htsget-http` structs.
* Move `CertificateKeyPair` to config to avoid repeating the logic in `htsget-tests` and simplifying logic in `htsget-search`. This is a breaking change as it removes the `TryFrom<DataServerConfig> for HttpTicketFormatter` implementation.
=> refactor!: refactor tests to avoid a circular dependency with htsget-search and htsget-http

Cargo.lock, htsget-actix/Cargo.toml, htsget-config/Cargo.toml, htsget-http/Cargo.toml, htsget-lambda/Cargo.toml, htsget-search/Cargo.toml, htsget-test/Cargo.toml
Makes htsget-test a regular dependency rather than a dev-dependency to address issues in publishing crates.
=> build: make htsget-test a regular dependency

htsget-search/src/htsget/bam_search.rs
Adds a warning when a non-valid PL read group header is found in `bam_search`.
=> refactor(search): add warning when a non-valid PL read group header is found

Cargo.lock, htsget-config/README.md
* A small doc update which includes a row for the endpoint option when configuring `S3Storage`.
=> docs(config): add documentation for endpoint when using S3 storage

htsget-actix/Cargo.toml, htsget-config/Cargo.toml, htsget-http/Cargo.toml, htsget-lambda/Cargo.toml, htsget-search/Cargo.toml, htsget-test/Cargo.toml
* Fixes `tower-http` not having the `fs` feature flag in `htsget-search`, which caused a build error.
=> fix(search): add fs feature to tower-http dependency

.github/workflows/benchmarking.yml, .github/workflows/tests.yml, Cargo.lock, Cargo.toml, htsget-actix/Cargo.toml, htsget-config/Cargo.toml, htsget-config/src/config/cors.rs, htsget-config/src/resolver.rs, htsget-config/src/storage/url.rs, htsget-http/Cargo.toml, htsget-lambda/Cargo.toml, htsget-lambda/src/lib.rs, htsget-search/Cargo.toml, htsget-search/src/htsget/bam_search.rs, htsget-search/src/htsget/bcf_search.rs, htsget-search/src/htsget/cram_search.rs, htsget-search/src/htsget/from_storage.rs, htsget-search/src/htsget/mod.rs, htsget-search/src/htsget/search.rs, htsget-search/src/htsget/vcf_search.rs, htsget-search/src/storage/local.rs, htsget-search/src/storage/mod.rs, htsget-search/src/storage/s3.rs, htsget-search/src/storage/url.rs, htsget-test/Cargo.toml, htsget-test/src/server_tests.rs
* Update noodles to latest version and remove some unused code in `htsget-search`.
* Use a `hyper::Client` instead of `reqwest::Client` for `UrlStorage`.
* Update dependencies to latest versions and update MSRV
=> refactor: dependencies

.github/workflows/build.yml, htsget-config/examples/config-files/url_storage.toml, htsget-config/src/types.rs, htsget-search/src/storage/mod.rs, htsget-search/src/storage/url.rs
* Fix URL responses so that headers are correctly forwarded from the client.
* Fix cache creation on the main branch for the build workflow.
=> fix: URL response headers

.github/workflows/benchmarking.yml, .github/workflows/build.yml, .github/workflows/release.yml, .github/workflows/tests.yml, Cargo.lock
This should've been part of https://github.com/umccr/htsget-rs/pull/185.
* Update `Cargo.lock`.
=> build: update Cargo.lock

.github/workflows/benchmarking.yml, .github/workflows/build.yml, .github/workflows/release.yml, .github/workflows/tests.yml
* Use dtolnay/rust-toolchain instead of actions-rs/toolchain.
=> ci: swap out toolchain actions

htsget-search/src/storage/url.rs
* Enables http/1.1 ALPN by using `enable_http1` and `enable_http2` instead of `enable_all_versions`.
=> fix(search): enable http/1.1 ALPN on UrlStorage client

htsget-search/src/htsget/bam_search.rs, htsget-search/src/htsget/bcf_search.rs, htsget-search/src/htsget/cram_search.rs, htsget-search/src/htsget/search.rs, htsget-search/src/htsget/vcf_search.rs
Closes #200 
* Ensure that valid header bytes are always returned by parsing and reading the header, and then determining the start of the next BGZF block.
* Add some tests for the header end offset.
=> fix: truncated header with larger files

htsget-search/src/htsget/bam_search.rs, htsget-search/src/htsget/bcf_search.rs, htsget-search/src/htsget/search.rs, htsget-search/src/htsget/vcf_search.rs
Closes #201 
* Return an empty response with header and EOF bytes when a reference name is found in the header but not the index, instead of returning an error.
* Add tests for this case.
* Fix filename for VCF tests.
=> fix(search): return empty response when reference name is in header

.gitignore, Cargo.lock
* Add Cargo.lock.
* Remove files that are not ignored from `.gitignore`.
* This caused the release to fail, because release-plz now considers `.gitignore` files when copying over to a tmp directory: https://github.com/MarcoIeni/release-plz/issues/1000
=> fix: release

Cargo.lock, htsget-actix/src/lib.rs, htsget-config/Cargo.toml, htsget-lambda/Cargo.toml, htsget-lambda/src/lib.rs, htsget-search/Cargo.toml, htsget-search/src/htsget/bam_search.rs, htsget-search/src/htsget/bcf_search.rs, htsget-search/src/htsget/search.rs, htsget-search/src/htsget/vcf_search.rs, htsget-test/Cargo.toml
* Update noodles to 0.60 and other small dependency changes.
* Fix clippy warnings.
noodles 0.60 has some changes that are useful for the crypt4gh branch and I didn't want this to get too out of sync. I'm leaving out changes related to `http` 1.0, e.g. `hyper` 1.0, `tower` 0.5, `aws` 1.0, etc, because these are recent and quite large, so some of our other dependencies haven't introduced them yet.
=> build: update noodles and other dependencies

deploy/README.md, deploy/bin/settings.ts, deploy/lib/htsget-lambda-stack.ts, htsget-config/src/config/cors.rs
* Update wording and naming slightly to make it clear that a JWT authorizer is being used.
=> docs(deploy): make authorizer logic more clear

.github/workflows/benchmarking.yml, .github/workflows/build.yml, .github/workflows/release.yml, .github/workflows/tests.yml
* Use GITHUB_TOKEN to authenticate the benchmark action.
* Update action versions and remove actions-rs as it is no longer maintained.
=> ci: fix benchmark

Cargo.lock, htsget-config/Cargo.toml, htsget-search/Cargo.toml, htsget-search/src/htsget/bam_search.rs, htsget-search/src/htsget/cram_search.rs, htsget-test/Cargo.toml
* Updates noodles and removes the lenient read group `PL` parsing because noodles now allows this by default: https://github.com/zaeleus/noodles/issues/111#issuecomment-1910630432
=> build(deps): update noodles to 0.65

.github/workflows/release.yml, deploy/Dockerfile, deploy/Dockerfile.dockerignore, deploy/README.md, deploy/compose.yml, deploy/config/dev_umccr.toml, deploy/config/prod_umccr.toml, deploy/config/public_umccr.toml, deploy/docker-compose.yml, deploy/examples/local_storage/README.md, deploy/examples/local_storage/compose.yml, deploy/examples/minio/README.md, deploy/examples/minio/compose.yml, deploy/examples/minio/config.toml, htsget-config/README.md, htsget-config/examples/config-files/s3_storage.toml, htsget-config/src/storage/mod.rs
Fixes #231 
* Add complete MinIO example with a docker compose showing specific configuration considerations.
* Minimise docker image by using `gcr.io/distroless/cc-debian12`.
* Rearrange examples and some README instructions.
* Remove differing behaviour of the default storage type when compiling with and without the `s3-storage` feature flag.
=> docs: docker minio example

.github/workflows/release.yml
Should:
* Not significantly increase runtimes by using QEMU, [prefer native machines instead](https://docs.docker.com/build/building/multi-platform/).
* Preferably avoid multiple docker containers, just ship one that is multiplatform.
=> ARM docker releases via GHA

.github/workflows/release.yml, deploy/Dockerfile
Outcome of this PR w.r.t SOCI is that we don't have layers < 10MB (total docker image size is currently ~50MB), so no `ztocs` indexes are generated and the CI build fails. If and when the layers grow in the future, we can re-evaluate this.
https://github.com/opencontainers/image-spec/blob/main/annotations.md
https://aws.amazon.com/blogs/containers/under-the-hood-lazy-loading-container-images-with-seekable-oci-and-aws-fargate/
https://github.com/awslabs/soci-snapshotter/discussions/949
=> Tweak docker container labels (was: Docker SOCI support)

htsget-config/README.md, htsget-config/examples/config-files/default.toml, htsget-config/src/config/mod.rs, htsget-config/src/resolver.rs, htsget-config/src/storage/local.rs
Closes #239, there's no need for the defaults to be any more complicated than a 1-1 mapping.
* Change default resolvers to `.*` and `$0`, and default local storage locations to the current directory.
* When running with default settings, data can still be fetched from `data/.../<id>`.
* Docker examples also work with a 1-1 mapping between the mount point and url paths.
=> refactor: simplify default resolvers and local storage data

htsget-config/README.md, htsget-config/src/resolver.rs, htsget-config/src/storage/url.rs, htsget-search/src/htsget/from_storage.rs, htsget-search/src/storage/url.rs
This PR introduces the ability to define headers that should not be forwarded when `forward_headers` is enabled, as described in issue #243.
```
...
[resolvers.storage]
url = "http://localhost:8080"
response_url = "https://example.com"
forward_headers = true
header_blacklist = ["Host"]
...
```
=> UrlStorage blacklist of forwarded headers

deploy/README.md, deploy/bin/settings.ts, deploy/lib/htsget-lambda-stack.ts, deploy/package-lock.json, deploy/package.json, deploy/tsconfig.json
Closes #242 
It turns out zig is still required, even though `cargo-lambda` prompts to install it, because the `RustFunction` construct doesn't support interactivity. Could potentially automate this by simulating 'enter' presses to install zig, but I don't think it's a good idea without user input.
* Swap out [rust.aws-cdk-lambda](https://github.com/rnag/rust.aws-cdk-lambda) for [cargo-lambda-cdk](https://github.com/cargo-lambda/cargo-lambda-cdk) because of slightly better automation when installing rustup targets and building release.
* Update `package.json` dependencies, including removing `@aws-cdk/aws-apigatewayv2-alpha` as it's no longer alpha.
=> docs: update deployment README

deploy/config/example_deploy.toml
* Allows fetching both C4GH and regular files in the resolvers settings. Previously this was always attempting to get C4GH files even if the directory contained regular files.
=> fix(deploy): allow fetching C4GH and regular files

CONTRIBUTING.md, README.md, SECURITY.md, htsget-actix/README.md, htsget-axum/README.md, htsget-config/README.md, htsget-config/examples/config-files/basic.toml, htsget-config/src/config/parser.rs, htsget-config/src/types.rs, htsget-http/README.md, htsget-lambda/README.md, htsget-search/README.md, htsget-storage/README.md, htsget-test/README.md
Starting with this, I'll leave the deploy directory for another PR.
* Simplify and re-word the docs.
* Add quick starts for runnable crates.
* Add some clarifying comments for complicated sections like config resolvers.
=> docs: re-word and simplify, add quick starts where applicable

docker/Dockerfile
Related to #309 
* Update rust version to 1.88 in Dockerfile
=> build: upgrade docker rust version

htsget-actix/src/lib.rs, htsget-axum/src/server/data.rs, htsget-axum/src/server/ticket.rs, htsget-config/README.md, htsget-config/docs/examples/default.toml, htsget-config/src/config/advanced/auth/mod.rs, htsget-config/src/config/advanced/regex_location.rs, htsget-config/src/config/data_server.rs, htsget-config/src/config/location.rs, htsget-config/src/config/mod.rs, htsget-config/src/storage/file.rs, htsget-config/src/storage/mod.rs, htsget-http/src/lib.rs, htsget-search/src/from_storage.rs, htsget-storage/src/lib.rs, htsget-storage/src/local.rs, htsget-test/src/http/mod.rs
Closes #319 
* Adds a ticket_origin option that allows changing the ticket response endpoint for local file-based locations.
* The server should forward the JWT on ticket responses if authorisation is being used.
* The data server should only perform authentication (not the custom authorization scheme) if it is confirmed.
* The interaction between `file://` locations and the data server was broken and difficult to configure correctly. I've re-worked it so that only one local directory can be used, and that always corresponds to data served by the data server (otherwise it's a configuration error).
* The data server is automatically disabled if not using `file://` locations, and the server's directory is also automatically matched to any `file://` location
=> feat: ticket origin and misc fixes

.github/workflows/docker.yml
Sould fix https://github.com/umccr/htsget-rs/actions/runs/16981443346 CI permissions error.
The newly introduced workflow permissions by #317 broke this (I guess?)... @mmalenic, caution, there might be similar side effects for the issues we're recently experiencing with release-plz?
=> Packages must be writable from the workflow
